# DATATHON Terra Journey — Grupo 48

## Preparação e consolidação da base PEDE

Este notebook realiza o tratamento das planilhas **PEDE2022**, **PEDE2023** e **PEDE2024** disponibilizadas no arquivo Excel do Datathon.

O fluxo executado contempla:

- leitura de todas as abas do arquivo de origem;
- levantamento e comparação das estruturas anuais;
- conversão de campos de ano, idade e índices;
- padronização dos nomes das colunas;
- consolidação das três bases em um único DataFrame;
- normalização de textos, gênero, fase, fase ideal e instituição de ensino;
- criação das colunas unificadas `Pedra` e `INDE`;
- recuperação e validação do índice `IPP`;
- preservação das colunas que contenham `pedra` durante a remoção de atributos com poucos dados;
- exportação da base consolidada em formato CSV, utilizando vírgula como separador.

O resultado é uma base única e padronizada para as etapas posteriores de análise exploratória, modelagem e geração de insights.

## 1. Importação das bibliotecas

São importadas as bibliotecas utilizadas para:

- manipulação e análise dos dados com `pandas` e `numpy`;
- tratamento de expressões e textos com `re` e `unicodedata`;
- agrupamento das estruturas das abas com `defaultdict`.

In [1]:
import pandas as pd
import numpy as np
import re
import unicodedata
from collections import defaultdict

## 2. Definição das funções auxiliares

Nesta etapa são definidas as funções responsáveis por:

- ler todas as abas do arquivo Excel e registrar informações estruturais;
- comparar os conjuntos de colunas entre as planilhas;
- remover colunas com quantidade de valores não nulos abaixo do limite informado, preservando aquelas que contenham `pedra` no nome;
- converter campos de ano, idade e índice;
- padronizar ou criar colunas de acordo com o ano de referência;
- normalizar gênero, fase, fase ideal e instituição de ensino;
- criar as colunas consolidadas `Pedra` e `INDE`;
- atualizar o `IPP` com base na composição do `INDE`;
- salvar o resultado final em CSV.

In [2]:
def ler_planilhas_excel_xlsx(github):
    excel = pd.ExcelFile(github, engine='openpyxl')

    planilhas = {}
    info_abas = {}

    for aba in excel.sheet_names:

        df = pd.read_excel(excel, sheet_name=aba)
        planilhas[aba] = df

        info_abas[aba] = {
            'nome_aba': aba,
            'num_linhas': len(df),
            'num_colunas': len(df.columns),
            'nome_colunas': list(df.columns),
            'tipos': {coluna: str(df[coluna].dtype) for coluna in df.columns},
            'nulos': {coluna: df[coluna].isnull().sum() for coluna in df.columns}
        }

    return planilhas, info_abas

In [3]:
def validar_colunas(dict_info_abas):
    grupos = defaultdict(list)

    for aba, info in info_abas.items():
        colunas = tuple(sorted(info['nome_colunas']))
        grupos[colunas].append(aba)

    for i, (colunas, abas) in enumerate(grupos.items(), start=1):
        print(f"\nGrupo {i}")
        print(f"Abas: {abas}")
        print(f"Quantidade de colunas: {len(colunas)}")
        print("Colunas:")
        for coluna in colunas:
            print(f" - {coluna}")

    grupos_lista = list(grupos.items())

    for i in range(len(grupos_lista)):
        colunas_i, abas_i = grupos_lista[i]

        for j in range(i + 1, len(grupos_lista)):
            colunas_j, abas_j = grupos_lista[j]

            set_i = set(colunas_i)
            set_j = set(colunas_j)

            print(f"\nComparação: Grupo {i+1} x Grupo {j+1}")
            print(f"Abas grupo {i+1}: {abas_i}")
            print(f"Abas grupo {j+1}: {abas_j}")
            print(f"Só no grupo {i+1}: {sorted(set_i - set_j)}")
            print(f"Só no grupo {j+1}: {sorted(set_j - set_i)}")

In [4]:
def remover_colunas_poucos_dados(df, minimo_non_null):

    excecoes = [
        'pedra',
        'ing'
    ]

    colunas_remover = df.columns[
        df.count() < minimo_non_null
    ]

    colunas_remover = [
        coluna
        for coluna in colunas_remover
        if not any(
            excecao in coluna.lower()
            for excecao in excecoes
        )
    ]

    print(f'{len(colunas_remover)} colunas removidas:')
    print(colunas_remover)

    return df.drop(columns=colunas_remover)

In [5]:
def converter_campo(df, coluna, tipo):

    def converter_valor(valor):

        if pd.isna(valor):
            return pd.NA

        if tipo == 'ano':

            data = pd.to_datetime(
                valor,
                errors='coerce'
            )

            if pd.isna(data):
                return pd.NA

            if (
                data.year == 1970
                and data.month == 1
                and data.day == 1
            ):
                return data.microsecond * 1000 + data.nanosecond

            return data.year

        if tipo == 'idade':

            if isinstance(valor, pd.Timestamp):

                if (
                    valor.year == 1900
                    and valor.month == 1
                ):
                    return valor.day

            data = pd.to_datetime(
                str(valor).strip(),
                errors='coerce'
            )

            if (
                pd.notna(data)
                and data.year == 1900
                and data.month == 1
            ):
                return data.day

            numero = pd.to_numeric(
                valor,
                errors='coerce'
            )

            if pd.notna(numero):
                return int(numero)

            return pd.NA

        if tipo == 'indice':
            numero = pd.to_numeric(
                valor,
                errors='coerce'
            )

            if pd.notna(numero):
                return float(numero)

            return pd.NA

        return pd.NA

    df[coluna] = df[coluna].apply(
        converter_valor
    )

    if tipo in [
        'ano',
        'idade'
    ]:
        df[coluna] = df[coluna].astype(
            'Int64'
        )

    if tipo == 'indice':
        df[coluna] = df[coluna].astype(
            'Float64'
        )

    return df

In [6]:
def ajustar_coluna(
    df,
    acao,
    coluna_destino=None,
    colunas_origem=None,
    tipo=None,
    colunas_atualizar=None
):

    df = df.copy()

    mapeamento_dados = {
        'Menino': 'M',
        'Menina': 'F',
        'Masculino': 'M',
        'Feminino': 'F',

        'Publica': 'Publica',
        'Escola Publica': 'Publica',
        'Privada - Programa De Apadrinhamento': 'Bolsista',
        'Privada *Parcerias Com Bolsa 100%': 'Bolsista',
        'Privada - Pagamento Por *Empresa Parceira': 'Bolsista',
        'Bolsista Universitario *Formado (A)': 'Bolsista',
        'Rede Decisao': 'Privada',
        'Privada': 'Privada',
        'Escola Jp Ii': 'Privada',
        'Concluiu O 3O Em': 'Outros',
        'Nenhuma Das Opcoes Acima': 'Outros'
    }

    tratamentos_colunas = {
        'fase': 'fase',
        'fase_ideal': 'fase',
        'genero': 'genero',
        'instituicao_ensino': 'instituicao_ensino',
        'ano_referencia': 'ano_referencia'
    }

    def normalizar_fase(fase):

        if pd.isna(fase):
            return pd.NA

        fase = str(fase).strip().upper()

        if fase == '':
            return pd.NA

        if fase == '0' or fase.startswith('ALFA'):
            return 'Alfa'

        if fase.startswith('FASE'):

            partes = (
                fase
                .replace('FASE', '')
                .strip()
                .split()
            )

            if len(partes) == 0:
                return pd.NA

            numero = partes[0]

            if numero.isdigit():
                return f'Fase {min(int(numero), 8)}'

            return pd.NA

        if fase[0].isdigit() and len(fase) > 1:

            numero = int(fase[0])

            return f'Fase {min(numero, 8)}'

        if fase.isdigit():

            numero = int(fase)

            return f'Fase {min(numero, 8)}'

        return pd.NA

    def converter_valor(
        valor,
        tipo_valor,
        tratamento=None
    ):

        if pd.isna(valor):

            if tratamento == 'instituicao_ensino':
                return 'Outros'

            return pd.NA

        if tratamento == 'ano_referencia':

            valor = str(valor).strip()

            ano = valor[-4:]

            if ano.isdigit():
                return int(ano)

            return pd.NA

        if tipo_valor == 'outros':
            return valor

        if tipo_valor == 'string':

            valor = (
                unicodedata.normalize(
                    'NFKD',
                    str(valor).strip()
                )
                .encode('ascii', 'ignore')
                .decode('utf-8')
            )

            valor = ' '.join(valor.split())

            if valor.upper() == 'INCLUIR':
                return pd.NA

            if tratamento == 'fase':
                return normalizar_fase(valor)

            valor = valor.title()

            if tratamento in [
                'genero',
                'instituicao_ensino'
            ]:
                return mapeamento_dados.get(
                    valor,
                    valor
                )

            return valor

        valor = str(valor).strip()

        if valor.upper() == 'INCLUIR':
            return pd.NA

        if tipo_valor == 'int':
            return int(float(valor))

        if tipo_valor == 'float':
            return float(valor)

        return valor

    if acao == 'criar':

        if coluna_destino is None:
            raise ValueError(
                'Informe coluna_destino para a ação criar.'
            )

        if colunas_origem is None:
            raise ValueError(
                'Informe colunas_origem para a ação criar.'
            )

        if tipo is None:
            raise ValueError(
                'Informe tipo para a ação criar.'
            )

        tratamento = tratamentos_colunas.get(
            coluna_destino.lower()
        )

        def obter_valor(linha):

            ano = linha['Ano_Referencia']

            coluna_origem = colunas_origem.get(
                ano
            )

            if coluna_origem is None:
                return pd.NA

            return converter_valor(
                linha[coluna_origem],
                tipo,
                tratamento
            )

        df[coluna_destino] = df.apply(
            obter_valor,
            axis=1
        )

    elif acao == 'atualizar':

        if colunas_atualizar is None:
            raise ValueError(
                'Informe colunas_atualizar para a ação atualizar.'
            )

        for coluna in colunas_atualizar:

            if coluna not in df.columns:
                raise KeyError(
                    f'A coluna {coluna} não existe no DataFrame.'
                )

            tratamento = tratamentos_colunas.get(
                coluna.lower()
            )

            if (
                pd.api.types.is_string_dtype(
                    df[coluna]
                )
                or pd.api.types.is_object_dtype(
                    df[coluna]
                )
            ):
                tipo_coluna = 'string'

            elif pd.api.types.is_integer_dtype(
                df[coluna]
            ):
                tipo_coluna = 'int'

            elif pd.api.types.is_float_dtype(
                df[coluna]
            ):
                tipo_coluna = 'float'

            else:
                tipo_coluna = 'outros'

            df[coluna] = df[coluna].apply(
                lambda valor: converter_valor(
                    valor,
                    tipo_coluna,
                    tratamento
                )
            )

    else:
        raise ValueError(
            "A ação deve ser 'criar' ou 'atualizar'."
        )

    return df

In [7]:
def atualizar_ipp(df):

    df = df.copy()

    def calcular_ipp(linha):

        ano = str(linha['Ano_Referencia'])[-4:]

        if (
            ano != '2022'
            and pd.notna(linha['IPP'])
        ):
            return linha['IPP']

        if  ano == '2022':
            fase_max = 7
        else:
            fase_max = 8

        indices = ['IAN', 'IDA', 'IEG', 'IAA', 'IPS', 'INDE']

        if linha[indices].isna().any():
            return pd.NA

        idade = linha['Idade']
        defasagem = linha['Defasagem']
        fase = str(
            linha['Fase']
        ).replace(
            'Fase',
            ''
        ).strip()

        if fase == 'Alfa':
            numero_fase = 0
        else:
            numero_fase = int(fase)

        ra = linha['RA']
        fase_new = linha['Fase']

        if numero_fase == fase_max:

            resultado = (
                (linha['IAN'] * 0.1) +
                (linha['IDA'] * 0.4) +
                (linha['IEG'] * 0.2) +
                (linha['IAA'] * 0.1) +
                (linha['IPS'] * 0.2) -
                linha['INDE']
            )

            print(
                f'Check1 RA: {ra} | '
                f'Idade: {idade} | '
                f'Fase: {fase} | '
                f'Defasagem: {defasagem} | '
                f'Resultado: {resultado:.4f}'
            )

            if resultado == 0:
                return pd.NA

        ipp_new = abs(
            (
                (linha['IAN'] * 0.1) +
                (linha['IDA'] * 0.2) +
                (linha['IEG'] * 0.2) +
                (linha['IAA'] * 0.1) +
                (linha['IPS'] * 0.1) +
                (linha['IPV'] * 0.2) -
                linha['INDE']
            ) * 10
        )

        if 0 <= ipp_new <= 0.2:

            print(
                f'Check2 RA: {ra} | '
                f'Idade: {idade} | '
                f'Fase: {fase} | '
                f'Defasagem: {defasagem} | '
                f'Resultado: {ipp_new:.4f}'
            )

            return pd.NA

        return ipp_new

    df['IPP'] = df.apply(
        calcular_ipp,
        axis=1
    )

    return df

In [8]:
def salvar_csv(df, nome_arquivo):
    df.to_csv(
        nome_arquivo,
        index=False,
        sep=',',
        encoding='utf-8-sig'
    )
    print(f'Arquivo salvo com sucesso: {nome_arquivo}')

## 3. Leitura da base de dados

O arquivo Excel é lido diretamente do repositório no GitHub. Cada aba é armazenada no dicionário `planilhas`, enquanto as informações de estrutura são armazenadas em `info_abas`.

Em seguida, a função `validar_colunas` agrupa abas com estruturas iguais e apresenta as diferenças de colunas entre os grupos.

In [9]:
github =  'https://raw.githubusercontent.com/andersonserrico/Datathon_TerraJourney_Grupo48/main/dados/BASE_DATATHON_2024.xlsx'

planilhas, info_abas = ler_planilhas_excel_xlsx(github)
validar_colunas(info_abas)

Grupo 1
Abas: ['PEDE2022']
Quantidade de colunas: 42
Colunas:
 - Ano ingresso
 - Ano nasc
 - Atingiu PV
 - Avaliador1
 - Avaliador2
 - Avaliador3
 - Avaliador4
 - Cf
 - Cg
 - Ct
 - Defas
 - Destaque IDA
 - Destaque IEG
 - Destaque IPV
 - Fase
 - Fase ideal
 - Gênero
 - IAA
 - IAN
 - IDA
 - IEG
 - INDE 22
 - IPS
 - IPV
 - Idade 22
 - Indicado
 - Inglês
 - Instituição de ensino
 - Matem
 - Nome
 - Nº Av
 - Pedra 20
 - Pedra 21
 - Pedra 22
 - Portug
 - RA
 - Rec Av1
 - Rec Av2
 - Rec Av3
 - Rec Av4
 - Rec Psicologia
 - Turma

Grupo 2
Abas: ['PEDE2023']
Quantidade de colunas: 48
Colunas:
 - Ano ingresso
 - Atingiu PV
 - Avaliador1
 - Avaliador2
 - Avaliador3
 - Avaliador4
 - Cf
 - Cg
 - Ct
 - Data de Nasc
 - Defasagem
 - Destaque IDA
 - Destaque IEG
 - Destaque IPV
 - Destaque IPV.1
 - Fase
 - Fase Ideal
 - Gênero
 - IAA
 - IAN
 - IDA
 - IEG
 - INDE 2023
 - INDE 22
 - INDE 23
 - IPP
 - IPS
 - IPV
 - Idade
 - Indicado
 - Ing
 - Instituição de ensino
 - Mat
 - Nome Anonimizado
 - Nº Av
 - Pedra 20
 - Pedra 2023
 - Pedra 21
 - Pedra 22
 - Pedra 23
 - Por
 - RA
 - Rec Av1
 - Rec Av2
 - Rec Av3
 - Rec Av4
 - Rec Psicologia
 - Turma

Grupo 3
Abas: ['PEDE2024']
Quantidade de colunas: 50
Colunas:
 - Ano ingresso
 - Atingiu PV
 - Ativo/ Inativo
 - Ativo/ Inativo.1
 - Avaliador1
 - Avaliador2
 - Avaliador3
 - Avaliador4
 - Avaliador5
 - Avaliador6
 - Cf
 - Cg
 - Ct
 - Data de Nasc
 - Defasagem
 - Destaque IDA
 - Destaque IEG
 - Destaque IPV
 - Escola
 - Fase
 - Fase Ideal
 - Gênero
 - IAA
 - IAN
 - IDA
 - IEG
 - INDE 2024
 - INDE 22
 - INDE 23
 - IPP
 - IPS
 - IPV
 - Idade
 - Indicado
 - Ing
 - Instituição de ensino
 - Mat
 - Nome Anonimizado
 - Nº Av
 - Pedra 20
 - Pedra 2024
 - Pedra 21
 - Pedra 22
 - Pedra 23
 - Por
 - RA
 - Rec Av1
 - Rec Av2
 - Rec Psicologia
 - Turma

Comparação: Grupo 1 x Grupo 2
Abas grupo 1: ['PEDE2022']
Abas grupo 2: ['PEDE2023']
Só no grupo 1: ['Ano nasc', 'Defas', 'Fase ideal', 'Idade 22', 'Inglês', 'Matem', 'Nome', 'Portug']
Só no grupo 2: ['Data de Nasc', 'Defasagem', 'Destaque IPV.1', 'Fase Ideal', 'INDE 2023', 'INDE 23', 'IPP', 'Idade', 'Ing', 'Mat', 'Nome Anonimizado', 'Pedra 2023', 'Pedra 23', 'Por']

Comparação: Grupo 1 x Grupo 3
Abas grupo 1: ['PEDE2022']
Abas grupo 3: ['PEDE2024']
Só no grupo 1: ['Ano nasc', 'Defas', 'Fase ideal', 'Idade 22', 'Inglês', 'Matem', 'Nome', 'Portug', 'Rec Av3', 'Rec Av4']
Só no grupo 3: ['Ativo/ Inativo', 'Ativo/ Inativo.1', 'Avaliador5', 'Avaliador6', 'Data de Nasc', 'Defasagem', 'Escola', 'Fase Ideal', 'INDE 2024', 'INDE 23', 'IPP', 'Idade', 'Ing', 'Mat', 'Nome Anonimizado', 'Pedra 2024', 'Pedra 23', 'Por']

Comparação: Grupo 2 x Grupo 3
Abas grupo 2: ['PEDE2023']
Abas grupo 3: ['PEDE2024']
Só no grupo 2: ['Destaque IPV.1', 'INDE 2023', 'Pedra 2023', 'Rec Av3', 'Rec Av4']
Só no grupo 3: ['Ativo/ Inativo', 'Ativo/ Inativo.1', 'Avaliador5', 'Avaliador6', 'Escola', 'INDE 2024', 'Pedra 2024']

## 4. Inspeção das planilhas anuais

As abas **PEDE2022**, **PEDE2023** e **PEDE2024** são inspecionadas individualmente com `info()`, `head()` e `tail()`.

Essa verificação permite observar:

- quantidade de registros e colunas;
- nomes e tipos dos campos;
- presença de valores nulos;
- exemplos dos dados no início ou no final de cada planilha.

In [10]:
planilhas['PEDE2022'].info(10)

<class 'pandas.DataFrame'>
RangeIndex: 860 entries, 0 to 859
Data columns (total 42 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   RA                     860 non-null    str
 1   Fase                   860 non-null    int64
 2   Turma                  860 non-null    str
 3   Nome                   860 non-null    str
 4   Ano nasc               860 non-null    int64
 5   Idade 22               860 non-null    int64
 6   Gênero                 860 non-null    str
 7   Ano ingresso           860 non-null    int64
 8   Instituição de ensino  860 non-null    str
 9   Pedra 20               323 non-null    str
 10  Pedra 21               462 non-null    str
 11  Pedra 22               860 non-null    str
 12  INDE 22                860 non-null    float64
 13  Cg                     860 non-null    int64
 14  Cf                     860 non-null    int64
 15  Ct                     860 non-null    int64
 16  Nº Av                  860 non-null    int64
 17  Avaliador1             860 non-null    str
 18  Rec Av1                860 non-null    str
 19  Avaliador2             860 non-null    str
 20  Rec Av2                860 non-null    str
 21  Avaliador3             534 non-null    str
 22  Rec Av3                860 non-null    str
 23  Avaliador4             310 non-null    str
 24  Rec Av4                296 non-null    str
 25  IAA                    860 non-null    float64
 26  IEG                    860 non-null    float64
 27  IPS                    860 non-null    float64
 28  Rec Psicologia         860 non-null    str
 29  IDA                    860 non-null    float64
 30  Matem                  858 non-null    float64
 31  Portug                 858 non-null    float64
 32  Inglês                 283 non-null    float64
 33  Indicado               860 non-null    str
 34  Atingiu PV             860 non-null    str
 35  IPV                    860 non-null    float64
 36  IAN                    860 non-null    float64
 37  Fase ideal             860 non-null    str
 38  Defas                  860 non-null    int64
 39  Destaque IEG           860 non-null    str
 40  Destaque IDA           860 non-null    str
 41  Destaque IPV           860 non-null    str
dtypes: float64(10), int64(9), str(23)
memory usage: 581.2 KB

In [11]:
planilhas['PEDE2022'].head()

,RA,Fase,Turma,Nome,Ano nasc,Idade 22,Gênero,Ano ingresso,Instituição de ensino,Pedra 20,...,Inglês,Indicado,Atingiu PV,IPV,IAN,Fase ideal,Defas,Destaque IEG,Destaque IDA,Destaque IPV
0,RA-1,7,A,Aluno-1,2003,19,Menina,2016,Escola Pública,Ametista,...,6.0,Sim,Não,7.278,5.0,Fase 8 (Universitários),-1,Melhorar: Melhorar a sua entrega de lições de ...,Melhorar: Empenhar-se mais nas aulas e avaliaç...,Melhorar: Integrar-se mais aos Princípios Pass...
1,RA-2,7,A,Aluno-2,2005,17,Menina,2017,Rede Decisão,Ametista,...,9.7,Não,Não,6.778,10.0,Fase 7 (3º EM),0,Melhorar: Melhorar a sua entrega de lições de ...,Melhorar: Empenhar-se mais nas aulas e avaliaç...,Melhorar: Integrar-se mais aos Princípios Pass...
2,RA-3,7,A,Aluno-3,2005,17,Menina,2016,Rede Decisão,Ametista,...,6.9,Não,Não,7.556,10.0,Fase 7 (3º EM),0,Destaque: A sua boa entrega das lições de casa.,Melhorar: Empenhar-se mais nas aulas e avaliaç...,Destaque: A sua boa integração aos Princípios ...
3,RA-4,7,A,Aluno-4,2005,17,Menino,2017,Rede Decisão,Ametista,...,8.7,Não,Não,5.278,10.0,Fase 7 (3º EM),0,Melhorar: Melhorar a sua entrega de lições de ...,Melhorar: Empenhar-se mais nas aulas e avaliaç...,Melhorar: Integrar-se mais aos Princípios Pass...
4,RA-5,7,A,Aluno-5,2005,17,Menina,2016,Rede Decisão,Ametista,...,5.7,Não,Não,7.389,10.0,Fase 7 (3º EM),0,Destaque: A sua boa entrega das lições de casa.,Melhorar: Empenhar-se mais nas aulas e avaliaç...,Melhorar: Integrar-se mais aos Princípios Pass...

In [12]:
planilhas['PEDE2023'].info()

<class 'pandas.DataFrame'>
RangeIndex: 1014 entries, 0 to 1013
Data columns (total 48 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   RA                     1014 non-null   str
 1   Fase                   1014 non-null   str
 2   INDE 2023              931 non-null    float64
 3   Pedra 2023             931 non-null    str
 4   Turma                  1014 non-null   str
 5   Nome Anonimizado       1014 non-null   str
 6   Data de Nasc           1014 non-null   object
 7   Idade                  1014 non-null   object
 8   Gênero                 1014 non-null   str
 9   Ano ingresso           1014 non-null   int64
 10  Instituição de ensino  1014 non-null   str
 11  Pedra 20               240 non-null    str
 12  Pedra 21               335 non-null    str
 13  Pedra 22               600 non-null    str
 14  Pedra 23               0 non-null      float64
 15  INDE 22                600 non-null    float64
 16  INDE 23                0 non-null      float64
 17  Cg                     0 non-null      float64
 18  Cf                     0 non-null      float64
 19  Ct                     0 non-null      float64
 20  Nº Av                  938 non-null    float64
 21  Avaliador1             938 non-null    str
 22  Rec Av1                0 non-null      float64
 23  Avaliador2             938 non-null    str
 24  Rec Av2                0 non-null      float64
 25  Avaliador3             707 non-null    str
 26  Rec Av3                0 non-null      float64
 27  Avaliador4             334 non-null    str
 28  Rec Av4                0 non-null      float64
 29  IAA                    951 non-null    float64
 30  IEG                    938 non-null    float64
 31  IPS                    945 non-null    float64
 32  IPP                    938 non-null    float64
 33  Rec Psicologia         0 non-null      float64
 34  IDA                    937 non-null    float64
 35  Mat                    937 non-null    float64
 36  Por                    937 non-null    float64
 37  Ing                    334 non-null    float64
 38  Indicado               0 non-null      float64
 39  Atingiu PV             0 non-null      float64
 40  IPV                    938 non-null    float64
 41  IAN                    1014 non-null   float64
 42  Fase Ideal             1014 non-null   str
 43  Defasagem              1014 non-null   int64
 44  Destaque IEG           0 non-null      float64
 45  Destaque IDA           0 non-null      float64
 46  Destaque IPV           0 non-null      float64
 47  Destaque IPV.1         0 non-null      float64
dtypes: float64(29), int64(2), object(2), str(15)
memory usage: 495.2+ KB

In [13]:
planilhas['PEDE2023'].head()

,RA,Fase,INDE 2023,Pedra 2023,Turma,Nome Anonimizado,Data de Nasc,Idade,Gênero,Ano ingresso,...,Indicado,Atingiu PV,IPV,IAN,Fase Ideal,Defasagem,Destaque IEG,Destaque IDA,Destaque IPV,Destaque IPV.1
0,RA-861,ALFA,9.31095,Topázio,ALFA A - G0/G1,Aluno-861,6/17/2015,8,Feminino,2023,...,NaN,NaN,8.920,10.0,ALFA (1° e 2° ano),0,NaN,NaN,NaN,NaN
1,RA-862,ALFA,8.22120,Topázio,ALFA A - G0/G1,Aluno-862,5/31/2014,9,Masculino,2023,...,NaN,NaN,8.585,5.0,Fase 1 (3° e 4° ano),-1,NaN,NaN,NaN,NaN
2,RA-863,ALFA,5.92975,Quartzo,ALFA A - G0/G1,Aluno-863,2/25/2016,7,Masculino,2023,...,NaN,NaN,6.260,10.0,ALFA (1° e 2° ano),0,NaN,NaN,NaN,NaN
3,RA-864,ALFA,7.03400,Ametista,ALFA A - G0/G1,Aluno-864,2015-12-03 00:00:00,1900-01-08 00:00:00,Feminino,2023,...,NaN,NaN,8.500,10.0,ALFA (1° e 2° ano),0,NaN,NaN,NaN,NaN
4,RA-865,ALFA,8.15520,Topázio,ALFA A - G0/G1,Aluno-865,11/13/2014,8,Masculino,2023,...,NaN,NaN,7.915,10.0,ALFA (1° e 2° ano),0,NaN,NaN,NaN,NaN

In [14]:
planilhas['PEDE2024'].info()

<class 'pandas.DataFrame'>
RangeIndex: 1156 entries, 0 to 1155
Data columns (total 50 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   RA                     1156 non-null   str
 1   Fase                   1156 non-null   object
 2   INDE 2024              1092 non-null   object
 3   Pedra 2024             1092 non-null   str
 4   Turma                  1156 non-null   object
 5   Nome Anonimizado       1156 non-null   str
 6   Data de Nasc           1156 non-null   datetime64[us]
 7   Idade                  1156 non-null   int64
 8   Gênero                 1156 non-null   str
 9   Ano ingresso           1156 non-null   int64
 10  Instituição de ensino  1155 non-null   str
 11  Pedra 20               191 non-null    str
 12  Pedra 21               264 non-null    str
 13  Pedra 22               472 non-null    str
 14  Pedra 23               690 non-null    str
 15  INDE 22                472 non-null    float64
 16  INDE 23                690 non-null    float64
 17  Cg                     0 non-null      float64
 18  Cf                     0 non-null      float64
 19  Ct                     0 non-null      float64
 20  Nº Av                  1156 non-null   int64
 21  Avaliador1             1029 non-null   str
 22  Rec Av1                0 non-null      float64
 23  Avaliador2             1029 non-null   str
 24  Rec Av2                0 non-null      float64
 25  Avaliador3             793 non-null    str
 26  Avaliador4             407 non-null    str
 27  Avaliador5             148 non-null    str
 28  Avaliador6             6 non-null      str
 29  IAA                    1054 non-null   float64
 30  IEG                    1156 non-null   float64
 31  IPS                    1054 non-null   float64
 32  IPP                    1054 non-null   float64
 33  Rec Psicologia         0 non-null      float64
 34  IDA                    1055 non-null   float64
 35  Mat                    1051 non-null   float64
 36  Por                    1050 non-null   float64
 37  Ing                    474 non-null    float64
 38  Indicado               0 non-null      float64
 39  Atingiu PV             0 non-null      float64
 40  IPV                    1054 non-null   float64
 41  IAN                    1156 non-null   float64
 42  Fase Ideal             1156 non-null   str
 43  Defasagem              1156 non-null   int64
 44  Destaque IEG           0 non-null      float64
 45  Destaque IDA           0 non-null      float64
 46  Destaque IPV           0 non-null      float64
 47  Escola                 1155 non-null   str
 48  Ativo/ Inativo         1156 non-null   str
 49  Ativo/ Inativo.1       1156 non-null   str
dtypes: datetime64[us](1), float64(23), int64(4), object(3), str(19)
memory usage: 626.1+ KB

In [15]:
planilhas['PEDE2024'].tail()

,RA,Fase,INDE 2024,Pedra 2024,Turma,Nome Anonimizado,Data de Nasc,Idade,Gênero,Ano ingresso,...,IPV,IAN,Fase Ideal,Defasagem,Destaque IEG,Destaque IDA,Destaque IPV,Escola,Ativo/ Inativo,Ativo/ Inativo.1
1151,RA-1658,9,INCLUIR,INCLUIR,9,Aluno-1658,2002-12-14 02:00:00,21,Masculino,2021,...,NaN,10.0,Fase 8 (Universitários),1,NaN,NaN,NaN,Faculdade (FIAP),Cursando,Cursando
1152,RA-1659,9,INCLUIR,INCLUIR,9,Aluno-1659,2003-02-04 02:00:00,21,Masculino,2021,...,NaN,10.0,Fase 8 (Universitários),1,NaN,NaN,NaN,Bolsista Universitário *Formado (a),Cursando,Cursando
1153,RA-1252,9,INCLUIR,INCLUIR,9,Aluno-1252,2002-06-03 03:00:00,22,Feminino,2021,...,NaN,10.0,Fase 8 (Universitários),1,NaN,NaN,NaN,Faculdade (FIAP),Cursando,Cursando
1154,RA-1660,9,INCLUIR,INCLUIR,9,Aluno-1660,2000-06-28 03:00:00,24,Feminino,2021,...,NaN,10.0,Fase 8 (Universitários),1,NaN,NaN,NaN,Bolsista Universitário *Formado (a),Cursando,Cursando
1155,RA-1661,9,INCLUIR,INCLUIR,9,Aluno-1661,2003-01-29 02:00:00,21,Feminino,2021,...,NaN,10.0,Fase 8 (Universitários),1,NaN,NaN,NaN,Bolsista Universitário *Formado (a),Cursando,Cursando

## 5. Conversão de campos

Alguns campos possuem formatos diferentes entre os anos e são convertidos antes da padronização dos nomes:

- em **PEDE2023**, `Data de Nasc` é convertida para ano e `Idade` para inteiro anulável;
- em **PEDE2024**, `Data de Nasc` é convertida para ano e `INDE 2024` para número decimal anulável.

A função `converter_campo` também trata datas anômalas usadas para representar ano ou idade.

In [16]:
#Conversao Ano_2023
converter_campo(planilhas['PEDE2023'], 'Data de Nasc', 'ano')
converter_campo(planilhas["PEDE2023"], "Idade", "idade")

#Conversao Ano_2024
converter_campo(planilhas['PEDE2024'], 'Data de Nasc', 'ano')
converter_campo(planilhas['PEDE2024'], 'INDE 2024', 'indice')

,RA,Fase,INDE 2024,Pedra 2024,Turma,Nome Anonimizado,Data de Nasc,Idade,Gênero,Ano ingresso,...,IPV,IAN,Fase Ideal,Defasagem,Destaque IEG,Destaque IDA,Destaque IPV,Escola,Ativo/ Inativo,Ativo/ Inativo.1
0,RA-1275,ALFA,7.611367,Ametista,ALFA A - G0/G1,Aluno-1275,2016,8,Masculino,2024,...,5.446667,10.0,ALFA (1° e 2° ano),0,NaN,NaN,NaN,EE Chácara Florida II,Cursando,Cursando
1,RA-1276,ALFA,8.002867,Topázio,ALFA A - G0/G1,Aluno-1276,2016,8,Feminino,2024,...,7.050000,10.0,ALFA (1° e 2° ano),0,NaN,NaN,NaN,EE Chácara Florida II,Cursando,Cursando
2,RA-1277,ALFA,7.9522,Ametista,ALFA A - G0/G1,Aluno-1277,2016,8,Masculino,2024,...,7.046667,10.0,ALFA (1° e 2° ano),0,NaN,NaN,NaN,EE Dom Pedro Villas Boas de Souza,Cursando,Cursando
3,RA-868,ALFA,7.156367,Ametista,ALFA A - G0/G1,Aluno-868,2015,8,Masculino,2023,...,7.213333,5.0,Fase 1 (3° e 4° ano),-1,NaN,NaN,NaN,EE Chácara Florida II,Cursando,Cursando
4,RA-1278,ALFA,5.4442,Quartzo,ALFA A - G0/G1,Aluno-1278,2015,9,Masculino,2024,...,4.173333,5.0,Fase 1 (3° e 4° ano),-1,NaN,NaN,NaN,EM Etelvina Delfim Simões,Cursando,Cursando
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1151,RA-1658,9,<NA>,INCLUIR,9,Aluno-1658,2002,21,Masculino,2021,...,NaN,10.0,Fase 8 (Universitários),1,NaN,NaN,NaN,Faculdade (FIAP),Cursando,Cursando
1152,RA-1659,9,<NA>,INCLUIR,9,Aluno-1659,2003,21,Masculino,2021,...,NaN,10.0,Fase 8 (Universitários),1,NaN,NaN,NaN,Bolsista Universitário *Formado (a),Cursando,Cursando
1153,RA-1252,9,<NA>,INCLUIR,9,Aluno-1252,2002,22,Feminino,2021,...,NaN,10.0,Fase 8 (Universitários),1,NaN,NaN,NaN,Faculdade (FIAP),Cursando,Cursando
1154,RA-1660,9,<NA>,INCLUIR,9,Aluno-1660,2000,24,Feminino,2021,...,NaN,10.0,Fase 8 (Universitários),1,NaN,NaN,NaN,Bolsista Universitário *Formado (a),Cursando,Cursando
1155,RA-1661,9,<NA>,INCLUIR,9,Aluno-1661,2003,21,Feminino,2021,...,NaN,10.0,Fase 8 (Universitários),1,NaN,NaN,NaN,Bolsista Universitário *Formado (a),Cursando,Cursando

A conversão mantém valores inválidos ou ausentes como `pd.NA` e utiliza os tipos anuláveis `Int64` e `Float64` quando aplicável.

## 6. Padronização dos nomes das colunas

Um único dicionário de mapeamento renomeia atributos equivalentes que possuem nomes diferentes entre os anos.

A padronização abrange:

- identificação e dados pessoais;
- fase, fase ideal e defasagem;
- notas de Português, Matemática e Inglês;
- recomendações e destaques;
- índices anuais do `INDE`;
- classificações anuais de `Pedra`;
- situação de atividade e demais campos auxiliares.

In [17]:
mapeamento_colunas = {
    # Identificação
    'Nome': 'Nome',
    'Nome Anonimizado': 'Nome',

    # Dados pessoais
    'Ano nasc': 'Ano_Nascimento',
    'Data de Nasc': 'Ano_Nascimento',
    'Idade 22': 'Idade',
    'Idade': 'Idade',

    # Indicadores
    'Defas': 'Defasagem',
    'Defasagem': 'Defasagem',

    'Fase ideal': 'Fase_Ideal',
    'Fase Ideal': 'Fase_Ideal',

    # Disciplinas
    'Inglês': 'Ing',
    'Ing': 'Ing',

    'Matem': 'Mat',
    'Mat': 'Mat',

    'Portug': 'Por',
    'Por': 'Por',

    'Gênero': 'Genero',
    'Ano ingresso': 'Ano_Ingresso',
    'Instituição de ensino': 'Instituicao_Ensino',
    'Nº Av': 'Num_Av',

    'Rec Av1': 'Rec_Av1',
    'Rec Av2': 'Rec_Av2',
    'Rec Av3': 'Rec_Av3',
    'Rec Av4': 'Rec_Av4',
    'Rec Av5': 'Rec_Av5',
    'Rec Av6': 'Rec_Av6',
    'Rec Psicologia': 'Rec_Psicologia',

    'Atingiu PV': 'Atingiu_PV',

    'Destaque IEG': 'Destaque_IEG',
    'Destaque IDA': 'Destaque_IDA',
    'Destaque IPV': 'Destaque_IPV',

    # Índices
    'INDE 20'  : 'INDE_20',
    'INDE 21'  : 'INDE_21',
    'INDE 22'  : 'INDE_22',
    'INDE 23'  : 'INDE_23_1',
    'INDE 2023': 'INDE_23',
    'INDE 2024': 'INDE_24',

    'Pedra 20'  : 'Pedra_20',
    'Pedra 21'  : 'Pedra_21',
    'Pedra 22'  : 'Pedra_22',
    'Pedra 23'  : 'Pedra_23_1',
    'Pedra 2023': 'Pedra_23',
    'Pedra 2024': 'Pedra_24',

    # Outros
    'Ativo/ Inativo': 'Ativo_Inativo',
    'Ativo/ Inativo.1': 'Ativo_Inativo_1',

    'Destaque IPV.1': 'Destaque_IPV_1',
}

for nome_aba, df in planilhas.items():
    df.rename(columns=mapeamento_colunas, inplace=True)

## 7. Validação após a renomeação

Após aplicar o dicionário de colunas em todas as abas, a estrutura de cada DataFrame é novamente verificada com `info()`.

O objetivo é confirmar os novos nomes, os tipos dos dados e as diferenças que ainda permanecem entre os anos antes da integração.

In [18]:
planilhas['PEDE2022'].info()

<class 'pandas.DataFrame'>
RangeIndex: 860 entries, 0 to 859
Data columns (total 42 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   RA                  860 non-null    str
 1   Fase                860 non-null    int64
 2   Turma               860 non-null    str
 3   Nome                860 non-null    str
 4   Ano_Nascimento      860 non-null    int64
 5   Idade               860 non-null    int64
 6   Genero              860 non-null    str
 7   Ano_Ingresso        860 non-null    int64
 8   Instituicao_Ensino  860 non-null    str
 9   Pedra_20            323 non-null    str
 10  Pedra_21            462 non-null    str
 11  Pedra_22            860 non-null    str
 12  INDE_22             860 non-null    float64
 13  Cg                  860 non-null    int64
 14  Cf                  860 non-null    int64
 15  Ct                  860 non-null    int64
 16  Num_Av              860 non-null    int64
 17  Avaliador1          860 non-null    str
 18  Rec_Av1             860 non-null    str
 19  Avaliador2          860 non-null    str
 20  Rec_Av2             860 non-null    str
 21  Avaliador3          534 non-null    str
 22  Rec_Av3             860 non-null    str
 23  Avaliador4          310 non-null    str
 24  Rec_Av4             296 non-null    str
 25  IAA                 860 non-null    float64
 26  IEG                 860 non-null    float64
 27  IPS                 860 non-null    float64
 28  Rec_Psicologia      860 non-null    str
 29  IDA                 860 non-null    float64
 30  Mat                 858 non-null    float64
 31  Por                 858 non-null    float64
 32  Ing                 283 non-null    float64
 33  Indicado            860 non-null    str
 34  Atingiu_PV          860 non-null    str
 35  IPV                 860 non-null    float64
 36  IAN                 860 non-null    float64
 37  Fase_Ideal          860 non-null    str
 38  Defasagem           860 non-null    int64
 39  Destaque_IEG        860 non-null    str
 40  Destaque_IDA        860 non-null    str
 41  Destaque_IPV        860 non-null    str
dtypes: float64(10), int64(9), str(23)
memory usage: 581.2 KB

In [19]:
planilhas['PEDE2023'].info()

<class 'pandas.DataFrame'>
RangeIndex: 1014 entries, 0 to 1013
Data columns (total 48 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   RA                  1014 non-null   str
 1   Fase                1014 non-null   str
 2   INDE_23             931 non-null    float64
 3   Pedra_23            931 non-null    str
 4   Turma               1014 non-null   str
 5   Nome                1014 non-null   str
 6   Ano_Nascimento      1014 non-null   Int64
 7   Idade               1014 non-null   Int64
 8   Genero              1014 non-null   str
 9   Ano_Ingresso        1014 non-null   int64
 10  Instituicao_Ensino  1014 non-null   str
 11  Pedra_20            240 non-null    str
 12  Pedra_21            335 non-null    str
 13  Pedra_22            600 non-null    str
 14  Pedra_23_1          0 non-null      float64
 15  INDE_22             600 non-null    float64
 16  INDE_23_1           0 non-null      float64
 17  Cg                  0 non-null      float64
 18  Cf                  0 non-null      float64
 19  Ct                  0 non-null      float64
 20  Num_Av              938 non-null    float64
 21  Avaliador1          938 non-null    str
 22  Rec_Av1             0 non-null      float64
 23  Avaliador2          938 non-null    str
 24  Rec_Av2             0 non-null      float64
 25  Avaliador3          707 non-null    str
 26  Rec_Av3             0 non-null      float64
 27  Avaliador4          334 non-null    str
 28  Rec_Av4             0 non-null      float64
 29  IAA                 951 non-null    float64
 30  IEG                 938 non-null    float64
 31  IPS                 945 non-null    float64
 32  IPP                 938 non-null    float64
 33  Rec_Psicologia      0 non-null      float64
 34  IDA                 937 non-null    float64
 35  Mat                 937 non-null    float64
 36  Por                 937 non-null    float64
 37  Ing                 334 non-null    float64
 38  Indicado            0 non-null      float64
 39  Atingiu_PV          0 non-null      float64
 40  IPV                 938 non-null    float64
 41  IAN                 1014 non-null   float64
 42  Fase_Ideal          1014 non-null   str
 43  Defasagem           1014 non-null   int64
 44  Destaque_IEG        0 non-null      float64
 45  Destaque_IDA        0 non-null      float64
 46  Destaque_IPV        0 non-null      float64
 47  Destaque_IPV_1      0 non-null      float64
dtypes: Int64(2), float64(29), int64(2), str(15)
memory usage: 497.2 KB

In [20]:
planilhas['PEDE2024'].info()

<class 'pandas.DataFrame'>
RangeIndex: 1156 entries, 0 to 1155
Data columns (total 50 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   RA                  1156 non-null   str
 1   Fase                1156 non-null   object
 2   INDE_24             1054 non-null   Float64
 3   Pedra_24            1092 non-null   str
 4   Turma               1156 non-null   object
 5   Nome                1156 non-null   str
 6   Ano_Nascimento      1156 non-null   Int64
 7   Idade               1156 non-null   int64
 8   Genero              1156 non-null   str
 9   Ano_Ingresso        1156 non-null   int64
 10  Instituicao_Ensino  1155 non-null   str
 11  Pedra_20            191 non-null    str
 12  Pedra_21            264 non-null    str
 13  Pedra_22            472 non-null    str
 14  Pedra_23_1          690 non-null    str
 15  INDE_22             472 non-null    float64
 16  INDE_23_1           690 non-null    float64
 17  Cg                  0 non-null      float64
 18  Cf                  0 non-null      float64
 19  Ct                  0 non-null      float64
 20  Num_Av              1156 non-null   int64
 21  Avaliador1          1029 non-null   str
 22  Rec_Av1             0 non-null      float64
 23  Avaliador2          1029 non-null   str
 24  Rec_Av2             0 non-null      float64
 25  Avaliador3          793 non-null    str
 26  Avaliador4          407 non-null    str
 27  Avaliador5          148 non-null    str
 28  Avaliador6          6 non-null      str
 29  IAA                 1054 non-null   float64
 30  IEG                 1156 non-null   float64
 31  IPS                 1054 non-null   float64
 32  IPP                 1054 non-null   float64
 33  Rec_Psicologia      0 non-null      float64
 34  IDA                 1055 non-null   float64
 35  Mat                 1051 non-null   float64
 36  Por                 1050 non-null   float64
 37  Ing                 474 non-null    float64
 38  Indicado            0 non-null      float64
 39  Atingiu_PV          0 non-null      float64
 40  IPV                 1054 non-null   float64
 41  IAN                 1156 non-null   float64
 42  Fase_Ideal          1156 non-null   str
 43  Defasagem           1156 non-null   int64
 44  Destaque_IEG        0 non-null      float64
 45  Destaque_IDA        0 non-null      float64
 46  Destaque_IPV        0 non-null      float64
 47  Escola              1155 non-null   str
 48  Ativo_Inativo       1156 non-null   str
 49  Ativo_Inativo_1     1156 non-null   str
dtypes: Float64(1), Int64(1), float64(23), int64(4), object(2), str(19)
memory usage: 628.3+ KB

## 8. Integração das bases

As três planilhas são concatenadas verticalmente em `df_unificado`.

Durante a consolidação:

- o nome da aba de origem é registrado inicialmente na coluna `Ano`;
- essa coluna é renomeada para `Ano_Referencia`;
- as principais variáveis de identificação são posicionadas no início;
- as demais colunas mantêm a ordem relativa existente após a concatenação.

A coluna `Ano_Referencia` mantém os valores `PEDE2022`, `PEDE2023` e `PEDE2024`. Nas funções posteriores, os quatro últimos caracteres são utilizados para identificar o ano correspondente.

In [21]:
df_unificado = pd.concat(

    [

        df.assign(Ano=nome_aba)

        for nome_aba, df in planilhas.items()

    ],

    ignore_index=True,

    sort=False

)

# Renomeia a coluna
df_unificado.rename(columns={'Ano': 'Ano_Referencia'}, inplace=True)

# Ordem desejada para as primeiras colunas
colunas_inicio = [
    'RA',
    'Fase',
    'Turma',
    'Nome',
    'Ano_Nascimento',
    'Idade',
    'Genero',
    'Ano_Ingresso',
    'Instituicao_Ensino',
    'Ano_Referencia'
]

# Demais colunas permanecem na ordem atual
outras_colunas = [
    col for col in df_unificado.columns
    if col not in colunas_inicio
]

# Reorganiza o DataFrame
df_unificado = df_unificado[colunas_inicio + outras_colunas]

## 9. Validação inicial da base consolidada

A estrutura do DataFrame unificado é inspecionada para verificar a quantidade total de registros, as colunas resultantes, os tipos dos campos e a disponibilidade dos dados após a concatenação.

In [22]:
df_unificado.info()

<class 'pandas.DataFrame'>
RangeIndex: 3030 entries, 0 to 3029
Data columns (total 56 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   RA                  3030 non-null   str
 1   Fase                3030 non-null   object
 2   Turma               3030 non-null   object
 3   Nome                3030 non-null   str
 4   Ano_Nascimento      3030 non-null   Int64
 5   Idade               3030 non-null   Int64
 6   Genero              3030 non-null   str
 7   Ano_Ingresso        3030 non-null   int64
 8   Instituicao_Ensino  3029 non-null   str
 9   Ano_Referencia      3030 non-null   str
 10  Pedra_20            754 non-null    str
 11  Pedra_21            1061 non-null   str
 12  Pedra_22            1932 non-null   str
 13  INDE_22             1932 non-null   float64
 14  Cg                  860 non-null    float64
 15  Cf                  860 non-null    float64
 16  Ct                  860 non-null    float64
 17  Num_Av              2954 non-null   float64
 18  Avaliador1          2827 non-null   str
 19  Rec_Av1             860 non-null    object
 20  Avaliador2          2827 non-null   str
 21  Rec_Av2             860 non-null    object
 22  Avaliador3          2034 non-null   str
 23  Rec_Av3             860 non-null    object
 24  Avaliador4          1051 non-null   str
 25  Rec_Av4             296 non-null    object
 26  IAA                 2865 non-null   float64
 27  IEG                 2954 non-null   float64
 28  IPS                 2859 non-null   float64
 29  Rec_Psicologia      860 non-null    object
 30  IDA                 2852 non-null   float64
 31  Mat                 2846 non-null   float64
 32  Por                 2845 non-null   float64
 33  Ing                 1091 non-null   float64
 34  Indicado            860 non-null    object
 35  Atingiu_PV          860 non-null    object
 36  IPV                 2852 non-null   float64
 37  IAN                 3030 non-null   float64
 38  Fase_Ideal          3030 non-null   str
 39  Defasagem           3030 non-null   int64
 40  Destaque_IEG        860 non-null    object
 41  Destaque_IDA        860 non-null    object
 42  Destaque_IPV        860 non-null    object
 43  INDE_23             931 non-null    float64
 44  Pedra_23            931 non-null    str
 45  Pedra_23_1          690 non-null    object
 46  INDE_23_1           690 non-null    float64
 47  IPP                 1992 non-null   float64
 48  Destaque_IPV_1      0 non-null      float64
 49  INDE_24             1054 non-null   Float64
 50  Pedra_24            1092 non-null   str
 51  Avaliador5          148 non-null    str
 52  Avaliador6          6 non-null      str
 53  Escola              1155 non-null   str
 54  Ativo_Inativo       1156 non-null   str
 55  Ativo_Inativo_1     1156 non-null   str
dtypes: Float64(1), Int64(2), float64(18), int64(2), object(13), str(20)
memory usage: 1.7+ MB

## 10. Padronização dos valores e criação dos indicadores consolidados

A função `ajustar_coluna` é aplicada às colunas textuais selecionadas para:

- remover acentos e espaços excedentes;
- padronizar a capitalização;
- converter valores `INCLUIR` em nulos;
- mapear gênero para `M` ou `F`;
- normalizar `Fase` e `Fase_Ideal` entre `Alfa` e `Fase 8`;
- classificar `Instituicao_Ensino` como `Publica`, `Privada`, `Bolsista` ou `Outros`, de acordo com o dicionário;
- transformar valores nulos de `Instituicao_Ensino` em `Outros`.

Também são criadas duas colunas unificadas por ano de referência:

- `Pedra`: utiliza `Pedra_22`, `Pedra_23` ou `Pedra_24`;
- `INDE`: utiliza `INDE_22`, `INDE_23` ou `INDE_24`.

A coluna `INDE_23` é convertida para o tipo numérico detectado pela função, e a coluna auxiliar `INDE_23_1` é removida após o processamento.

### Atualização do IPP

Para anos diferentes de 2022, valores de `IPP` já preenchidos são preservados. Nos demais casos, o cálculo depende da disponibilidade dos índices necessários.

Para a fase máxima de cada ano — `Fase 7` em 2022 e `Fase 8` nos demais anos — é verificada a expressão:

```text
(IAN × 0,1) + (IDA × 0,4) + (IEG × 0,2) + (IAA × 0,1) + (IPS × 0,2) − INDE
```

Quando o resultado é exatamente zero, o `IPP` é tratado como nulo.

Nos demais casos, o índice é recalculado por:

```text
IPP = |((IAN × 0,1) + (IDA × 0,2) + (IEG × 0,2) + (IAA × 0,1)
      + (IPS × 0,1) + (IPV × 0,2) − INDE) × 10|
```

Resultados entre `0` e `0,2`, inclusive, também são tratados como nulos. Os demais valores calculados são mantidos.

In [23]:
colunas_padronizar = [
    'Nome',
    'Genero',
    'Ano_Referencia',
    'Fase',
    'Fase_Ideal',
    'Instituicao_Ensino',
    'Turma',
    'Pedra_20',
    'Pedra_21',
    'Pedra_22',
    'Pedra_23',
    'Pedra_23_1',
    'Pedra_24',
    'Escola'
]

df_unificado = ajustar_coluna(
    df_unificado,
    acao='atualizar',
    colunas_atualizar=colunas_padronizar
)

df_unificado = ajustar_coluna(
    df_unificado,
    acao='criar',
    coluna_destino='Pedra',
    tipo='string',
    colunas_origem={
        2022: 'Pedra_22',
        2023: 'Pedra_23',
        2024: 'Pedra_24'
    }
)

df_unificado = ajustar_coluna(
    df_unificado,
    acao='criar',
    coluna_destino='INDE',
    tipo='float',
    colunas_origem={
        2022: 'INDE_22',
        2023: 'INDE_23',
        2024: 'INDE_24'
    }
)

colunas_indices = [
    'INDE_23'
]

df_unificado = ajustar_coluna(
    df_unificado,
    acao='atualizar',
    colunas_atualizar=colunas_indices
)

df_unificado = atualizar_ipp(df_unificado)

df_unificado.drop(
    columns=['INDE_23_1'],
    inplace=True
)

Check1 RA: RA-1 | Idade: 19 | Fase: 7 | Defasagem: -1 | Resultado: -0.9130
Check1 RA: RA-2 | Idade: 17 | Fase: 7 | Defasagem: 0 | Resultado: -0.1550
Check1 RA: RA-3 | Idade: 17 | Fase: 7 | Defasagem: 0 | Resultado: -0.6510
Check1 RA: RA-4 | Idade: 17 | Fase: 7 | Defasagem: 0 | Resultado: -0.0510
Check1 RA: RA-5 | Idade: 17 | Fase: 7 | Defasagem: 0 | Resultado: -0.7170
Check1 RA: RA-6 | Idade: 18 | Fase: 7 | Defasagem: -1 | Resultado: -0.8380
Check1 RA: RA-7 | Idade: 18 | Fase: 7 | Defasagem: -1 | Resultado: -0.0980
Check1 RA: RA-8 | Idade: 20 | Fase: 7 | Defasagem: -1 | Resultado: -0.7560
Check1 RA: RA-9 | Idade: 18 | Fase: 7 | Defasagem: -1 | Resultado: -0.6490
Check1 RA: RA-10 | Idade: 18 | Fase: 7 | Defasagem: -1 | Resultado: -0.7740
Check1 RA: RA-11 | Idade: 18 | Fase: 7 | Defasagem: -1 | Resultado: -0.8630
Check1 RA: RA-12 | Idade: 17 | Fase: 7 | Defasagem: 0 | Resultado: -1.0520
Check1 RA: RA-13 | Idade: 18 | Fase: 7 | Defasagem: -1 | Resultado: -0.7520
Check1 RA: RA-14 | Idade: 21 | Fase: 7 | Defasagem: -1 | Resultado: -0.7430
Check1 RA: RA-15 | Idade: 18 | Fase: 7 | Defasagem: -1 | Resultado: 0.0170
Check1 RA: RA-16 | Idade: 19 | Fase: 7 | Defasagem: -1 | Resultado: -0.7620
Check1 RA: RA-17 | Idade: 20 | Fase: 7 | Defasagem: -1 | Resultado: -0.0680
Check1 RA: RA-18 | Idade: 19 | Fase: 7 | Defasagem: -1 | Resultado: 0.5040
Check1 RA: RA-19 | Idade: 19 | Fase: 7 | Defasagem: -1 | Resultado: 0.2250
Check1 RA: RA-20 | Idade: 19 | Fase: 7 | Defasagem: -1 | Resultado: 0.0550
Check1 RA: RA-21 | Idade: 18 | Fase: 7 | Defasagem: -1 | Resultado: -0.6250
Check2 RA: RA-695 | Idade: 8 | Fase: Alfa | Defasagem: 0 | Resultado: 0.1000
Check2 RA: RA-751 | Idade: 11 | Fase: Alfa | Defasagem: -2 | Resultado: 0.0740

## 11. Validação das padronizações

As tabelas de contingência apresentam a distribuição anual das colunas consolidadas e padronizadas:

- `Pedra` por ano de referência;
- `Fase` por ano de referência;
- `Instituicao_Ensino` por ano de referência.

Também é exibida a frequência geral das categorias de instituição de ensino.

In [24]:
pd.crosstab(
    df_unificado['Ano_Referencia'],
    df_unificado['Pedra']
)

Pedra           Agata  Ametista  Quartzo  Topazio
Ano_Referencia
2022              250       348      132      130
2023              246       381       72      232
2024              225       391      112      326

In [25]:
pd.crosstab(
    df_unificado['Ano_Referencia'],
    df_unificado['Fase'].fillna('Sem Informação')
    )

Fase,Alfa,Fase 1,Fase 2,Fase 3,Fase 4,Fase 5,Fase 6,Fase 7,Fase 8
Ano_Referencia,,,,,,,,,
2022,190,192,155,148,76,60,18,21,0
2023,231,173,200,132,94,65,33,23,63
2024,196,185,185,211,115,100,25,37,102

In [26]:
pd.crosstab(
    df_unificado['Ano_Referencia'],
    df_unificado['Instituicao_Ensino'].fillna('Sem Informação')
    )

Instituicao_Ensino  Bolsista  Outros  Privada  Publica
Ano_Referencia
2022                       0       0      108      752
2023                     168       9       28      809
2024                     159       8       76      913

In [27]:
df_unificado['Instituicao_Ensino'].value_counts()

Instituicao_Ensino
Publica     2474
Bolsista     327
Privada      212
Outros        17
Name: count, dtype: int64

## 12. Remoção de colunas com poucos dados

São removidas as colunas que possuem menos de `1.500` valores não nulos.

Como exceção, qualquer coluna cujo nome contenha a palavra `pedra`, sem diferenciação entre maiúsculas e minúsculas, é preservada mesmo quando não atinge o limite definido.

Ao final, `info()` é executado novamente para validar a estrutura restante.

In [28]:
# Eliminar colunas com menos de 10 valores não nulos
minimo_non_null = 1500
df_unificado = remover_colunas_poucos_dados(df_unificado, minimo_non_null)

21 colunas removidas:
['Cg', 'Cf', 'Ct', 'Rec_Av1', 'Rec_Av2', 'Rec_Av3', 'Avaliador4', 'Rec_Av4', 'Rec_Psicologia', 'Indicado', 'Destaque_IEG', 'Destaque_IDA', 'Destaque_IPV', 'INDE_23', 'Destaque_IPV_1', 'INDE_24', 'Avaliador5', 'Avaliador6', 'Escola', 'Ativo_Inativo', 'Ativo_Inativo_1']

In [29]:
df_unificado.info()

<class 'pandas.DataFrame'>
RangeIndex: 3030 entries, 0 to 3029
Data columns (total 36 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   RA                  3030 non-null   str
 1   Fase                3030 non-null   str
 2   Turma               3030 non-null   str
 3   Nome                3030 non-null   str
 4   Ano_Nascimento      3030 non-null   Int64
 5   Idade               3030 non-null   Int64
 6   Genero              3030 non-null   str
 7   Ano_Ingresso        3030 non-null   int64
 8   Instituicao_Ensino  3030 non-null   str
 9   Ano_Referencia      3030 non-null   int64
 10  Pedra_20            754 non-null    str
 11  Pedra_21            1061 non-null   str
 12  Pedra_22            1932 non-null   str
 13  INDE_22             1932 non-null   float64
 14  Num_Av              2954 non-null   float64
 15  Avaliador1          2827 non-null   str
 16  Avaliador2          2827 non-null   str
 17  Avaliador3          2034 non-null   str
 18  IAA                 2865 non-null   float64
 19  IEG                 2954 non-null   float64
 20  IPS                 2859 non-null   float64
 21  IDA                 2852 non-null   float64
 22  Mat                 2846 non-null   float64
 23  Por                 2845 non-null   float64
 24  Ing                 1091 non-null   float64
 25  Atingiu_PV          860 non-null    object
 26  IPV                 2852 non-null   float64
 27  IAN                 3030 non-null   float64
 28  Fase_Ideal          3030 non-null   str
 29  Defasagem           3030 non-null   int64
 30  Pedra_23            931 non-null    str
 31  Pedra_23_1          690 non-null    str
 32  IPP                 2850 non-null   object
 33  Pedra_24            1054 non-null   str
 34  Pedra               2845 non-null   str
 35  INDE                2845 non-null   object
dtypes: Int64(2), float64(11), int64(3), object(3), str(17)
memory usage: 1.1+ MB

## 13. Exportação da base tratada

A base consolidada é exportada para o arquivo `PEDE_Dados_Unificados.csv`.

A gravação utiliza:

- vírgula como separador (`sep=','`);
- ausência do índice do DataFrame (`index=False`);
- codificação `utf-8-sig`, facilitando a abertura do arquivo em ferramentas como Excel sem perda de acentos.

In [30]:
salvar_csv(
    df_unificado,
    'PEDE_Dados_Unificados.csv'
)

Arquivo salvo com sucesso: PEDE_Dados_Unificados.csv